In [2]:
import numpy as np
import scipy

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [14]:
np.sign(a)

array([ 1,  1,  1,  1, -1, -1,  0,  0,  0, -1,  1, -1])

In [15]:
tbr = sum((a) < 0) #there are 4 negative numbers in the list

In [16]:
tbr

4

In [20]:
#2 how many positive numbers are there -> 5

In [21]:
tbrpos = sum((a > 0))

In [22]:
tbrpos

5

In [26]:
#3 how any EVEN, POSITIVE numbers are there -> 3 PosEven
tbrpe = sum((a > 0) & (a % 2 == 0))

In [27]:
tbrpe

3

In [35]:
#4 if you added 3 to each value, how any are POSITIVE -> 10 after +3
add_three = a + 3
a3_array = sum(add_three > 0)

In [37]:
a3_array

10

In [38]:
#5 if sq each number, what are new mean and stdv

In [92]:
sq_array = a**2
sq_array

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [50]:
import statistics as st
print("mean is: " + str(st.mean(sq_array)))
print("STDV is: " + str(st.stdev(sq_array)))

mean is: 74
STDV is: 150.42606157179014


In [51]:
#6 subtract mean from each data point

In [54]:
subtract_mean = (a - st.mean(a))
subtract_mean

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [55]:
#7 calculate the zscore

In [57]:
import scipy.stats as stats
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [58]:
#7 more numpy exercises

In [59]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [64]:
sum_of_a = sum(a)
sum_of_a

55

In [65]:
min_of_a = min(a)
min_of_a

1

In [68]:
max_of_a = max(a)
max_of_a

10

In [71]:
mean_of_a = st.mean(a)
mean_of_a

5.5

In [77]:
import numpy as np
product_of_a = np.prod(a)
product_of_a

3628800

In [84]:
squares_of_a = [] 
for i in a:
    squares_of_a.append(a[i-1]**2)

squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [88]:
odds_in_a = []
for i in a:
    if a[i-1] % 2 != 0:
        odds_in_a.append(a[i-1])
    
odds_in_a

[1, 3, 5, 7, 9]

In [89]:
evens_in_a = []
for i in a:
    if a[i-1] % 2 == 0:
        evens_in_a.append(a[i-1])
    
evens_in_a

[2, 4, 6, 8, 10]

In [ ]:
centering = a - st.mean(a)

In [ ]:
zscore = scipy.stats.zscore(a)